### ISSUE TITLE
Can I run it on Linux?

### ISSUE THREAD

**Issue by xoac** [automatak/dnp3-simulator#6]
On [nugat](https://www.nuget.org/packages/opendnp3#) site there is requirement  `Visual Studio 2015 C++ runtime` so it's impossible to run this simulator under Linux?

**Comment by jadamcrain** [comment]
No, it's windows only b/c the .NET bindings rely on Microsoft C++/cli.

**Comment by meeas** [comment]
Bubbling this to the top again.  Adam, doesn't Microsoft's .NET Core they released for Linux support that cli?  I know they made some changes to it in Core 2.1 but I thought the cli has been supported since they Core 1.0 release last year.

**Comment by jadamcrain** [comment]
I don't believe so:

https://github.com/dotnet/coreclr/issues/659

The pure CLR part would work, but there is no C++/CLI compiler for Linux.

**Comment by sidhoda** [comment]
To support cross platform .NET Core I believe the bindings would need to be updated to use PInvoke (DllImport) to interop with opendnp3 built as C++ dynamic library

**Comment by jadamcrain** [comment]
Correct.  This is a non-trivial undertaking, and I wouldn't even want to support it if someone created them.
